# Format: <Rectangle Pro action name> <modifier+modifier+key>
# Keys include a-z, 0-9, arrows, return, space, tab, escape, F1-F12, and keypad-enter.
almostMaximize                  control+option+command+return
